STARTING SCRIPT /home/hadoop/biggraphstage/kitescripts/big_data_tests/embeddedness.groovy with params List((testDataSet,fake_westeros_v3_5m_145m))
2016-10-19 15:36:58,671 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-7 
Lost executor 1 on ip-10-234-208-152.ec2.internal: Container marked as failed: container_1476889168652_0003_01_000002 on host: ip-10-234-208-152.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node
2016-10-19 15:42:56,610 - [ERROR] - from org.apache.spark.network.client.TransportClient in shuffle-server-2 
Failed to send RPC 8487488465056552949 to ip-10-79-218-20.ec2.internal/10.79.218.20:58774: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
2016-10-19 15:42:56,614 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-0 
Lost executor 2 on ip-10-79-218-20.ec2.internal: Slave lost
2016-10-19 15:42:56,691 - [ERROR] - from org.apache.spark.network.client.TransportClient in shuffle-server-2 
Failed to send RPC 6566026578148907687 to ip-10-79-218-20.ec2.internal/10.79.218.20:58774: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
2016-10-19 15:42:56,692 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-6 
Lost executor 4 on ip-10-168-247-160.ec2.internal: Slave lost
2016-10-19 15:42:57,205 - [ERROR] - from org.apache.spark.network.client.TransportClient in shuffle-server-2 
Failed to send RPC 8543295978465140086 to ip-10-79-218-20.ec2.internal/10.79.218.20:58774: java.nio.channels.ClosedChannelException
java.nio.channels.ClosedChannelException: null
2016-10-19 15:42:57,207 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-3 
Lost executor 3 on ip-10-178-216-29.ec2.internal: Slave lost
2016-10-19 15:46:10,754 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-5 
Lost executor 1 on ip-10-234-208-152.ec2.internal: Container marked as failed: container_1476889168652_0003_02_000002 on host: ip-10-234-208-152.ec2.internal. Exit status: 52. Diagnostics: Exception from container-launch.
Container id: container_1476889168652_0003_02_000002
Exit code: 52
Stack trace: ExitCodeException exitCode=52: 
at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
at org.apache.hadoop.util.Shell.run(Shell.java:455)
at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)


Container exited with a non-zero exit code 52

2016-10-19 15:59:03,020 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-2 
Lost executor 3 on ip-10-186-90-252.ec2.internal: Container marked as failed: container_1476889168652_0003_02_000004 on host: ip-10-186-90-252.ec2.internal. Exit status: -100. Diagnostics: Container released on a *lost* node
2016-10-19 15:59:06,327 - [ERROR] - from org.apache.spark.scheduler.cluster.YarnScheduler in dispatcher-event-loop-1 
Lost an executor 3 (already removed): Pending loss reason.
FINISHED SCRIPT /home/hadoop/biggraphstage/kitescripts/big_data_tests/embeddedness.groovy, took 1772 seconds
